### ISSUE TITLE
my Navigaton bar is not working for my app

### ISSUE THREAD

**Issue by baiyue789** [thuanvoit/spotify-sdk-tutorial#11]
![image](https://github.com/thuanvoit/spotify-sdk-tutorial/assets/73799464/5d11f5b7-37c1-4abf-abdd-e5f795074592)
My navigation bar is not working in my app. These are my files and navigation setting for other files I can only send screenshots since GitHub is not allowing me to send java files or xml.

**Comment by a-stickan** [comment]
@baiyue789 This does not relate to the Spotify API, closing this issue. Please post this on Ed and ask your mentor TA for help if you need it.
