### ISSUE TITLE
Blank Screen after Requesting Token

### ISSUE THREAD

**Issue by JuliaJ3** [thuanvoit/spotify-sdk-tutorial#13]
# Blank Screen after Requesting Token

## About
I am having issues with the Request Token button after it redirects to the accounts.spotify.com page. It keeps crashing and showing a blank screen, only to reload again. I have gone through all the troubleshooting tips and the Ed discussion for any solutions and none of them have worked. One of the tips said to change the emulator settings to increase the VM Heap (I have already changed it to Pixel 3a) but it is not editable in my settings. It may be an issue with my computer itself but I'm not sure what steps to take next.

### Gradle File
![image](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/156847930/2eb67e30-3a13-4167-bf5d-001c0ec99439)

### Java File
![image](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/156847930/c3f0fc09-9828-43bd-aa76-43e8b96a153f)

### SS of Spotify Dashboard Redirect UI
![image](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/156847930/0751ca91-e6fe-4a7a-b502-fb7140c64e95)

###Task Manager
![image](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/156847930/849631be-de8e-4f44-b0e5-9907f299e12d)

### Logcat
![image](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/156847930/ba3b9c4c-7a23-45cc-9027-41b533872b6f)

### Emulator Settings
![image](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/156847930/53da65f2-7f44-4ad2-bb32-9e8943073253)

**System OS**: Microsoft Windows 11 Home
**Android Studio version**: Android Studio Hedgehog | 2023.1.1 Patch 2

**Comment by a-stickan** [comment]
@JuliaJ3 Can your teammates run this code without any issues? That would help us confirm whether or not the error is unique to your emulator/system. Assuming the error is related to your emulator's memory, [I'd try increasing your VM heap using some of the solutions mentioned here.](https://stackoverflow.com/questions/45517553/cant-change-the-ram-size-in-avd-manager-android-studio)

**Comment by thuanvoit** [comment]
I would recommend [@a-stickan ](https://github.com/CS2340-SP24/spotify-sdk-tutorial/issues/13#issuecomment-2024311596) solution! Please let us know asap or the issue would be closed!

**Comment by JuliaJ3** [comment]
They also had issues running it but I think they tried something else for the API so everything is good now. Thank you!
