### ISSUE TITLE
Api response code

### ISSUE THREAD

**Issue by CURT1S03** [thuanvoit/spotify-sdk-tutorial#14]
I was able to get the api response code 200 (OK - The request has succeeded. The client can read the result of the request in the body and the headers of the response.) for one time, and then I run the program again I get code 403 (Unauthorized - The request requires user authentication or, if the request included authorization credentials, authorization has been refused for those credentials.) what could potentially be the issue
![Screenshot 2024-03-28 045451](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/152463808/950e6e28-1723-4a7a-a32f-2cd700ea5afb)
![image](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/152463808/53e7cf74-8bc7-4360-ac0c-a39df486c9e5)

**Comment by a-stickan** [comment]
@CURT1S03 A 403 forbidden indicates that either your token expired or you are attempting a request with inappropriate scopes. I would try refreshing your token and trying again, then double-checking that your scopes match the request's documentation

**Comment by CURT1S03** [comment]
I am able to get 200 when I log in again this morning and afternoon without any changes to the code. Is it possible that user can only be logged in once in a while

**Comment by CURT1S03** [comment]
> @CURT1S03 A 403 forbidden indicates that either your token expired or you are attempting a request with inappropriate scopes. I would try refreshing your token and trying again, then double-checking that your scopes match the request's documentation

**Comment by CURT1S03** [comment]
> @CURT1S03 A 403 forbidden indicates that either your token expired or you are attempting a request with inappropriate scopes. I would try refreshing your token and trying again, then double-checking that your scopes match the request's documentation

This issue has been fixed! I was using my teammates redirect uri and client id when logging into my account, changing those to mine fixed the issue

**Comment by CURT1S03** [comment]
> @CURT1S03 A 403 forbidden indicates that either your token expired or you are attempting a request with inappropriate scopes. I would try refreshing your token and trying again, then double-checking that your scopes match the request's documentation
