### ISSUE TITLE
Tutorial Functionality Only Works on the First Time I Run My App

### ISSUE THREAD

**Issue by itatikola** [thuanvoit/spotify-sdk-tutorial#15]
# Bug Report

## Spotify Redirect URI
spotifywrappedapplication://auth

## System OS
macOS Monterey

## Android Studio Version
Android Studio Hedgehog | 2023.1.1 Patch 1

## Problem
Our "Generate User Profile" button only works the first time after generating an API Token. After the first time, the app either crashes or just redirects to the Spotify log-in page when clicking "Get User Profile." When redirected, the actual "Log In" button is faded/non-clickable. Here is a video of me trying it for the first time, and then a second time. 

https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/62963846/3ac546f0-f56e-4f19-9ad9-d31fb0291a70

## Relevant Files

Here are the AndroidManifest.xml and MainActivity.java file in PDF format. 

[Spotify Tutorial Issue.pdf](https://github.com/CS2340-SP24/spotify-sdk-tutorial/files/14808778/Spotify.Tutorial.Issue.pdf)

**Comment by a-stickan** [comment]
@itatikola Please format your issue [according to the template](https://github.com/CS2340-SP24/spotify-sdk-tutorial/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). This looks like a potential redirect URI issue, but we need more information to be able to properly debug this

**Comment by itatikola** [comment]
---
| Syntax | Description |
| -------- | ----------- |
| name | Bug Report |
| about |  "Generate User Profile" button only works the first time after generating an API Token. After the first time, the app either crashes or just redirects to the Spotify log-in page when clicking "Get User Profile." |
| title | ? |
| labels | ? |
| assignees | @a-stickan |
---
# Bug Report

Issue is described above. I'm unsure how else to expand upon the bug. I can't attach the files because .java and .xml file types are not supported to attach to comments. They are unchanged from the initial issue.

**Comment by a-stickan** [comment]
@itatikola [**Please edit your original post to make it follow the template!**](https://github.com/CS2340-SP24/spotify-sdk-tutorial/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) We will start to debug your code once you provide all the necessary info mentioned in the template. Look at [some of our closed issues](https://github.com/CS2340-SP24/spotify-sdk-tutorial/issues?q=is%3Aissue+is%3Aclosed) to get a better idea on how to format your post

**Comment by itatikola** [comment]
Reformatted the original comment!

**Comment by a-stickan** [comment]
@itatikola Does this error occur for other team members?

_If other team members have the same issue_, I would follow the "Issues Getting Token/Code from Spotify" guide in our Troubleshooting Tips section. The error is likely due to a redirect URI issue, which we go over how to fix in there.

_If it only occurs on your device_, I recommend that you try wiping your emulator data and making a brand-new pixel 3A phone emulator. If that doesn't work, try reinstalling Android Studio. [If you still have errors at that point, please try some of these suggested fixes](https://stackoverflow.com/questions/58381078/error-for-android-emulator-deciding-if-gldirectmem-vulkan-should-be-enabled).

**Comment by itatikola** [comment]
Looks like this error is not happening for other team members. I tried wiping my emulator data and making a brand-new emulator, but still was having the same error. I think we're just gonna continue developing on other team member's computers.

**Comment by a-stickan** [comment]
@itatikola Pair-programming on other's laptops is always an option, but I'd try and avoid it unless you absolutely have to. Try the following fix before you give up:

Add the following lines to ~/.android/advancedFeatures.ini (create this file if it doesn't exist already):
```
Vulkan = off
GLDirectMem = on
```

**Comment by itatikola** [comment]
I think I'm still running into the same issue. Thank you for your efforts, though.

**Comment by thuanvoit** [comment]
I would recommend you to use debug feature. Try to create multiple breakpoints and watch how your data is populated! Keep us updated!
