### ISSUE TITLE
Attempting to edit VM heap, but the setting is locked

### ISSUE THREAD

**Issue by masonlouism** [thuanvoit/spotify-sdk-tutorial#16]
<img width="626" alt="image" src="https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/123116611/4075f658-c09d-4aab-9913-7e132273b3b0">

This image shows that my VM heap is currently unable to be changed. I am currently in the process of trying to fix a blank screen upon authentication, but this step is in the guide and I can't complete it.

**Comment by GavinG60** [comment]
Is this the Pixel 3a with the API 33 without the Google Play option? Some of the emulators don't let you edit it, make sure it is that one specifically

**Comment by thuanvoit** [comment]
I suggest to create a new device with new configuration!

**Comment by a-stickan** [comment]
@masonlouism Gavin and Thuan's suggestions should work. Another approach is manually changing the phone's VM heap in the emulator's associated `config.yml` file.

**Comment by thuanvoit** [comment]
@masonlouism Please give us update asap!

**Comment by masonlouism** [comment]
I resorted to using a newer emulator that allowed me to edit the VM heap. That solved my issue.
