### ISSUE TITLE
Spotify Scope Error

### ISSUE THREAD

**Issue by dhruv3745** [thuanvoit/spotify-sdk-tutorial#17]
When I do my api call to get the top songs I have listened to I get an insufficient Scope error: ' "error": {"status": 403, "message": "Insufficient client scope" }  '.

The [api call documentation](https://developer.spotify.com/documentation/web-api/reference/get-users-top-artists-and-tracks) states that the scope needed is user top read, which I do have in my scope. When I link my spotify account, it states that is needed when I agree to link the account. Other Api calls work with the exact same code except for the exact link I use.

The code where I make the call:
<img width="917" alt="Screenshot 2024-04-08 at 9 22 27 AM" src="https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/36820900/01b818f0-69fb-4fa4-9ae0-c66da8174c59">

The code where I set the scope:
<img width="854" alt="Screenshot 2024-04-08 at 9 22 51 AM" src="https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/36820900/95f0477b-260a-4caf-a46b-10044e2aa32d">

The Spotify screen:
<img width="310" alt="Screenshot 2024-04-08 at 9 23 31 AM" src="https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/36820900/d8f9d71f-72f5-4880-800f-e3ccb0a28c91">

**Comment by thuanvoit** [comment]
Can you remove custom parameter from the authorization request and test it again? Also, move the user-top-read to the very end of the list.
I think you need to create a new spotify app on the developer dashboard before trying it. What I'm trying to do is to move the scope to the end of the request URL.

**Comment by dhruv3745** [comment]
I made those changes and am on a different spotify app with me added to the new developer dashboard but I still am having the same error.

**Comment by dhruv3745** [comment]
Solved!

**Comment by thuanvoit** [comment]
@dhruv3745 How did you solve it? Can you share with us?
