### ISSUE TITLE
Emulator broken or Spotify Login Redirect errore

### ISSUE THREAD

**Issue by suryasmurali22** [thuanvoit/spotify-sdk-tutorial#18]
I am having trouble accessing spotify API. My redirect URIs and client ID match as they should. Our redirect URI is not the com.example.___ but it still lines up in all places.  but once got to google, my app crashes, we made all emulator changes as described in trouble shotting and nothing works. I am already runnin pixel 3A XL with no google or border stuff with increase VM.

Spotify Dashboard:
![734451137_1712759318307](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/156841913/14bfd185-0643-4b96-a029-700783617020)

Gradle App:
![image](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/156841913/48d5a6aa-de5a-44ac-b4d3-485a51a34d15)

Manifest:
![image](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/156841913/178c4d54-e571-4428-a7e6-e8e5f89fdea7)

Main Activity:
![image](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/156841913/ca32315a-1000-4d04-874f-e0ee9c47b315)

AS version: iguana

Emulator:
![image](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/156841913/2c6439bb-1b47-4d43-a09c-9c3cce9563e5)

Log cat:
![image](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/156841913/a1ae1bac-7cf1-4f6d-95b0-16a51642d02c)

**Comment by suryasmurali22** [comment]
I fixed code issue but emulator still breaks when I run and most of our group is experiencing this. I tried all ed post stuff and the emulator suggestions. It runs on TA Ians laptop just not ours

**Comment by a-stickan** [comment]
@suryasmurali22 This seems to be an error related to your emulator. To fix this I'd try the following:

1. Add the following code to C://Users/.../.android/advancedFeatures.ini (if the file doesn't already exist, create it manually)
```
Vulkan = off
GLDirectMem = on
```
2. Close down any unnecessary applications running in the background

**Comment by a-stickan** [comment]
@suryasmurali22 Closing this issue since I was able to resolve the error in class. If it reappears, please reopen this issue or make a new one!
