### ISSUE TITLE
Spotify API Call - User Recommendation

### ISSUE THREAD

**Issue by MosesTheRedSea** [thuanvoit/spotify-sdk-tutorial#19]
# Bug Report
Issue Making Spotify API Call

Essenitally I have a xml view called Reccomendations. 

![Screenshot 2024-04-12 142825](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/69429336/edf6a81c-a907-4eec-a1dd-c46b66ad725f)

In order to view this xml the user already has to be signedIn. I call a method titled 
retrieveSpotifyAccessTokenAndMakeRecommendation()

`
private void retrieveSpotifyAccessTokenAndMakeRecommendation() {

        retrieveSpotifyAccessTokenFromUserProfile(new OnTokenRetrievedListener() {
            @Override
            public void onTokenRetrieved(String spotifyAccessToken) {
                if (spotifyAccessToken != null) {
                    // Use the retrieved Spotify access token to make the recommendation request
                    makeRecommendationRequest(spotifyAccessToken);
                    Toast.makeText(firebaseUserManager.this, "Retrieved Spotify Token For Reccomendation", Toast.LENGTH_SHORT).show();
                } else {
                    // Handle the case where no Spotify access token was found
                    Toast.makeText(firebaseUserManager.this, "No Spotify access token found", Toast.LENGTH_SHORT).show();
                }
            }
        });
    }
`

It gets the user accessToken and calls a methdo which will create the recomendation.
This method successfully gets the spotifyAccessToken however it keeps failing whenever I make a call to get
the reccomendations for the user. Essentiall the Request is not working.

`
private void makeRecommendationRequest(String spotifyAccessToken) {

        OkHttpClient client = new OkHttpClient();

        // Define the request to the Spotify API
        Request request = new Request.Builder()
                .url("https://api.spotify.com/v1/recommendations?limit=10")
                .addHeader("Authorization", "Bearer " + spotifyAccessToken)
                .get() // Specify that this is a GET request
                .build();
        // Send the request asynchronously
        client.newCall(request).enqueue(new okhttp3.Callback() {
            @Override
            public void onFailure(okhttp3.Call call, IOException e) {
                e.printStackTrace();
                // Handle request failure
            }

            @Override
            public void onResponse(okhttp3.Call call, Response response) throws IOException {
                if (!response.isSuccessful()) {
                    throw new IOException("Unexpected code " + response);
                }

                Toast.makeText(firebaseUserManager.this, "Received Reccomendation", Toast.LENGTH_SHORT).show();

                try {
                    // Parse response JSON
                    String responseData = response.body().string();
                    List<String> recommendedTracks = parseRecommendations(responseData);

                    // Update UI with recommended tracks
                    runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            if (adapter != null) {
                                adapter.setRecommendedTracks(recommendedTracks); // Update the dataset with recommended tracks
                                adapter.notifyDataSetChanged(); // Notify the adapter that the dataset has changed
                            } else {
                                // If adapter is null, initialize it with the recommended tracks
                                adapter = new reccomendationAdapter(recommendedTracks, getApplicationContext()); // Pass recommended tracks to the constructor of your adapter
                                userReccomendation.setAdapter(adapter); // Set the adapter to your RecyclerView
                            }
                        }
                    });
                } catch (JSONException e) {
                    e.printStackTrace();
                    // Handle JSON parsing error
                }
            }
        });
    }
`

(UPDATE)
- Removed the RecycleVIew and Instead Decided to use ListView Displays Test Data Issue not just Spotify API Call

**Comment by a-stickan** [comment]
@MosesTheRedSea Looking at your code, I'm suspecting this is an issue with your parameters. The following parameters are all required in a request for song recommendations:

![image](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/84038418/6b505ba8-445d-4948-a575-a81fd73d0091)

**Comment by a-stickan** [comment]
Closing all issues since the Spring semester is now over
