### ISSUE TITLE
StreamResetException: stream was reset: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by SohamAg** [thuanvoit/spotify-sdk-tutorial#20]
Getting this exception when making calls. 

An idea what to do?

**Comment by a-stickan** [comment]
@SohamAg I responded to this in more detail in the email you sent me. Like I said there, I'd recommend making a new dashboard and seeing if that fixes your issue.

If that doesn't work, please respond to this email with the following information:
1. Screenshot of the error message
2. System OS
3. Android Studio version
4. Whether or not the issue appears for your teammates

**Comment by a-stickan** [comment]
Closing all issues since the Spring semester is now over
