### ISSUE TITLE
Spotify Token & User Request Failing, have tried everything

### ISSUE THREAD

**Issue by cpdiprete** [thuanvoit/spotify-sdk-tutorial#7]
###1. I followed tutorial troubleshooting, previous closed post on this github that had a similar issue, and attempted reaching out for ed discussion help to no avail. Every time I click the button to request a token or user profile, emulator goes wonky, always crashes but inconsistently, will reach different points and act differently almost every time I select the button to request a token. Ed discussion post asked me to recheck the troubleshooting tips from the tutorial again, and reach out here if the issue persisted, so I'm here. I'm seriously trying and struggling don't have a clue what to do at this point, help would be appreciated, thanks.

Github wont let me link my xml or java files, so I put them in a pdf, I can email them to someone if needed or post them on ed discussion.

- Any relevant Gradle files
- Any relevant Java files
- Screenshot of Spotify dashboard redirect URI:

[Github Help Files (1).pdf](https://github.com/thuanvoit/spotify-sdk-tutorial/files/14747762/Github.Help.Files.1.pdf)

- System OS: Windows 11
- Android Studio version: Hedgehog

**Comment by thuanvoit** [comment]
Based on your description, "emulator goes wonky, always crashes but inconsistently". I personally suggest you to edit your current emulator setting or create a new emulator with a higher VM Heap (e.g. 512 MB). 

<img width="618" alt="Screenshot 2024-03-25 at 2 45 06 PM" src="https://github.com/thuanvoit/spotify-sdk-tutorial/assets/21033636/21d06b9d-875c-4bc4-a7e0-328b1d33d8da">

**Comment by a-stickan** [comment]
@cpdiprete  Could you post a screenshot of task manager when you run the emulator? I'd like to make sure this isn't a bottlenecking issue with your hardware

**Comment by cpdiprete** [comment]
I edited the emulator like thuanvoit suggested and followed this ed discussion post and it seems that the app is finally working. 
![image](https://github.com/thuanvoit/spotify-sdk-tutorial/assets/156841549/b1737de3-2fa5-48ed-bbab-4e4c54f97fad)
Thanks for the help!
