### ISSUE TITLE
Spotify Token Request Login Button Not Working

### ISSUE THREAD

**Issue by josephkhanna** [thuanvoit/spotify-sdk-tutorial#9]
# Bug Report

## Screenshot of Spotify dashboard redirect URI:
<img width="353" alt="Screenshot 2024-03-25 at 7 22 38 PM" src="https://github.com/thuanvoit/spotify-sdk-tutorial/assets/133889399/6685b9d8-77c5-40bd-8f34-3e6a1022bf67">

## System OS: 
MacOS Sonoma

## Android Studio version: 
Hedgehog 2023.1.1 Patch 1

## Problem
The login button is still stuck and I cannot get to the next part. I know that the login function itself is working though, because when I clicked login, I got a confirmation email saying that I logged into a new device, as seen in the image below. Sometimes I cannot even get to the login screen and I am stuck on a white screen. It varies for each team member. **I increased VM Heap to 512 MB**, and I also tried the other troubleshooting tips, but that did not solve the problem. I tried on both Pixel 5 and Pixel 3A emulators.

![image](https://github.com/thuanvoit/spotify-sdk-tutorial/assets/133889399/843e4b36-e646-4d82-a163-09d97edfc927)

## Relevant Files
I am unable to upload .java or .xml or .gradle files to GitHub for some reason, but I can email them to anyone if needed.
Update: here is a PDF of the relevant files.
[relevantfilesissuereport.pdf](https://github.com/thuanvoit/spotify-sdk-tutorial/files/14750634/relevantfilesissuereport.pdf)

**Comment by thuanvoit** [comment]
Look like you have the old AndroidManfiest.xml and it sometimes doesn't work. We have just updated the tutorial for AndroidManifest.xml. Please take a look!

We notice that you got error detection at the `<data ... >` tag in your AndroidManifest.xml. Try to separate it into another `<intent-filter>`.

Good luck!

**Comment by josephkhanna** [comment]
Thank you for your help! I used the new AndroidManifest.xml instructions, but the login button is still stuck (I still got another new login notification proving that I am able to login). I am just unable to move past that screen.

**Comment by a-stickan** [comment]
@josephkhanna Does the tutorial code you have work when your teammates run it on their own systems? I'd like to rule out the possibility that this glitch is only present on your system

**Comment by thuanvoit** [comment]
One of our potential solutions for this issue is to use a package name for schemeName. Make sure to change schemeName everywhere we suggest.

[This picture](https://github.com/thuanvoit/spotify-sdk-tutorial?tab=readme-ov-file#redirect-uri-modifications)

**Comment by josephkhanna** [comment]
> @josephkhanna Does the tutorial code you have work when your teammates run it on their own systems? I'd like to rule out the possibility that this glitch is only present on your system

They all have the same issue

**Comment by josephkhanna** [comment]
> One of our potential solutions for this issue is to use a package name for schemeName. Make sure to change schemeName everywhere we suggest.
> 
> [This picture](https://github.com/thuanvoit/spotify-sdk-tutorial?tab=readme-ov-file#redirect-uri-modifications)

I just checked this; we used "SPOTIFY-TRIAL-RUN" as our package name and it seems to be correctly inserted into all those places. This may be unrelated but today we faced an issue when we realized our teammates who use Windows cannot even get the code to compile anymore. Could that have anything to do with this?

**Comment by thuanvoit** [comment]
[What is android app package name?](https://support.google.com/admob/answer/9972781?hl=en#:~:text=You%20can%20find%20an%20app%27s,example.)

This is your package name. 

![Screenshot 2024-03-26 at 11 37 03 PM](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/21033636/c3e5b8f9-0137-42e2-9ff3-f5684213bebb)

**Comment by thuanvoit** [comment]
> > One of our potential solutions for this issue is to use a package name for schemeName. Make sure to change schemeName everywhere we suggest.
> > [This picture](https://github.com/thuanvoit/spotify-sdk-tutorial?tab=readme-ov-file#redirect-uri-modifications)
> 
> I just checked this; we used "SPOTIFY-TRIAL-RUN" as our package name and it seems to be correctly inserted into all those places. This may be unrelated but today we faced an issue when we realized our teammates who use Windows cannot even get the code to compile anymore. Could that have anything to do with this?

[What is android app package name?](https://support.google.com/admob/answer/9972781?hl=en#:~:text=You%20can%20find%20an%20app%27s,example.)

This is your package name. 

![Screenshot 2024-03-26 at 11 37 03 PM](https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/21033636/c3e5b8f9-0137-42e2-9ff3-f5684213bebb)

**Comment by josephkhanna** [comment]
Thank you so much. I mixed up the existing redirect URI and the package name. Once I used the correct package name and edited my Spotify Developer settings to change my redirect URI to include that, my code started working.
